language: csharp
solution: GridOS.sln
install:
  - nuget restore GridOS.sln
script:
  - msbuild /p:Configuration=Release GridOS.sln
  - mono ./packages/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe ./tests/GridOS.UnitTests/bin/Release/GridOS.UnitTests.dll
